### PR TITLE
Add Redis session store example.

### LINKED ISSUE #6: Add documentation for Redis Store with example
Thanks to @Octo8080X work, we now have access to a Redis store for session.

We need to add some documentation (inspiration can be taken from the PR https://github.com/xstevenyung/fresh-session/pull/3) to help people understand how to work with it.

### PR DESCRIPTION
**Pull request by Octo8080X**
Hello, @xstevenyung.

I have created a sample that uses the Redis store.
(I apologize for having to recreate it.)

I have also created a README, so please follow it and try to run it.

Note that the following part of import _map.json is written for the next release.

```json
 "fresh-session/": "https://deno.land/x/fresh-session@0.1.8/"
```

If you try to run it, rewrite the following.

```json
"fresh-session/": "https://raw.githubusercontent.com/xstevenyung/fresh-session/main/"
```

https://github.com/xstevenyung/fresh-session/issues/6

### CODE REVIEW

**Comment by xstevenyung** [comment]
@Octo8080X could you "Allow edits from maintainers" (on the sidebar on the right). I would like to simplify a little bit the example to make it as easy as possible for newcomers

**Comment by excessivecoding** [comment]
@Octo8080X I'm not sure, but it seems like I can't make modification on your fork. Can you enable "Allow edits by maintainers" on the bottom right sidebar ?

I wanted to update a little bit your example to simplify for newcomers.

**Comment by Octo8080X** [comment]
@xstevenyung 
~~"Allow edits from maintainers" doesn't show up, so it looks a bit difficult. My apologies.~~
~~It may be due to the fact that I forked this repository as @Octo8080's Organization.~~

~~If you could put in a comment, I will try to fix it accordingly.~~

You have successfully set "Allow edits by maintainers". Please check again.

Thank you for your concern.

**Comment by Octo8080X** [comment]
Hello @xstevenyung .

enabled "Allow edits by maintainers".
Regards.

**Comment by excessivecoding** [comment]
Sorry @Octo8080X , I've not had time to do much open source lately.

We can always simplify the setup later, tbh it's good enough for now.

I will tag the next release for the redis store 👍

**Review by excessivecoding — APPROVED** [review]

**Pull request merged**
