### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by raLaaaa**
Proposed type fix.

### CODE REVIEW

**Comment by excessivecoding** [comment]
i guess both works, i would rather have it with `State` to show user how they can extend `WithSession`

thanks though !

**Comment by raLaaaa** [comment]
I also thought so at first. How ever what was a bit confusing for me is that the standart deno linter (atleast I think its a linting thing because the application runs with no errors) issues the following:

Assuming you have:

```
function sessionHandler(req: Request, ctx: MiddlewareHandlerContext<State>) {
  return session(req, ctx);
}
```

It errors `ctx` and says:

> Argument of type 'MiddlewareHandlerContext<State>' is not assignable to parameter of type 'MiddlewareHandlerContext<WithSession>'.
>   The types of 'state.session' are incompatible between these types.
>     Type 'WithSession' is missing the following properties from type 'Session': #data, #flash, #doDelete, data, and 8 more.

Since it is the default deno linter version that might be confusing. What do you think?

**Comment by excessivecoding** [comment]
Reopening to investigate, thanks for the feedback !

**Comment by raLaaaa** [comment]
Hit me up in case you need more information or testing 👍

**Pull request closed without merging**
